# Generated by Django 5.1.7 on 2025-03-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_applicant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='document_status',
            field=models.CharField(default='incomplete', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='resume_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='transcripts/'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='transcript_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
