# Generated by Django 5.1.7 on 2025-03-07 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0004_farm_remove_applicant_document_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('motivation_letter', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicants.applicant')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicants.farm')),
            ],
        ),
    ]
