# Generated by Django 5.1.7 on 2025-03-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0006_alter_farmapplication_options_remove_farm_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='country',
            field=models.CharField(default='Philippines', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
