# Generated by Django 5.1.7 on 2025-03-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0007_applicant_country_applicant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
