# Generated by Django 5.1.7 on 2025-03-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0009_applicant_resume_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farm_images/'),
        ),
    ]
