# Generated by Django 5.1.7 on 2025-03-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0012_remove_applicant_full_name_applicant_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmapplication',
            name='motivation_letter',
            field=models.TextField(blank=True),
        ),
    ]
